# Generated by Django 3.2 on 2021-04-09 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rename_order_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, null=True, verbose_name='order date')),
                ('subtotal', models.FloatField(null=True, verbose_name='subtotal')),
                ('taxes', models.FloatField(null=True, verbose_name='tax import')),
                ('paid', models.BooleanField(default=False, verbose_name='is_paid')),
                ('products', models.ManyToManyField(to='products.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-id'],
            },
        ),
    ]
